version: '3'
services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
            args:
              ASSETS_SOURCE_URL: "http://178.128.102.213/"
        container_name: nodejs
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app/
            - /usr/src/app/node_modules
    webserver:
        build: nginx/
        container_name: webserver
        restart: always
        ports:
            - "80:80"
        depends_on:
            - nodejs
        links:
            - express
