version: '3'
services:
    nodejs:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
              CMS_URL: "http://178.128.102.213"
        container_name: nodejs
        restart: always
        ports:
            - "3000:3000"
    webserver:
        build:
            context: nginx/
            dockerfile: nginx.dockerfile
        container_name: webserver
        restart: always
        ports:
            - "80:80"
        depends_on:
            - nodejs
        links:
            - nodejs
